name = "chatmanager-lead-worker"
main = "src/index.js"
compatibility_date = "2025-01-01"

[observability]
enabled = true

[[kv_namespaces]]
binding = "LEADS_DEDUP"
id = "c667c491c5bf4fe2b9ec2c7d075b37ce"